[package]
name = "termabc"
version = "0.1.0"
edition = "2024"

[dependencies]
termsize = { version = "0.1.9", optional = true }
defer-rs = { version = "0.1.0", optional = true }
unicode-segmentation = "1.12.0"

[dependencies.crossterm]
version = "0.29.0"
default-features = false
optional = true
